name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - master  # change this if your branch name is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USER }}/feedback-app .

    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USER }}/feedback-app

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USER }}/feedback-app
          docker stop feedback || true
          docker rm feedback || true
          docker run -d --name feedback -p 5000:5000 ${{ secrets.DOCKER_USER }}/feedback-app
